### PR TITLE
Feature accurate half stars

### PR DESCRIPTION
**Pull request by zhao0**
I have updated it to support storyboard and touch

### CODE REVIEW

**Comment by hsousa** [comment]
Hey man! Working better now! :+1: 

I found a bug: if you set the view's background color to `[UIColor clearColor]` it stops working as expected. I think this is because you're drawing a full highlighted star and then *cutting* the remaining rect using `backgroundColor`.

I figured out a good solution that works perfectly for images and paths. Can you give me access to your fork so I can push the changes? (that way the pull request has **all** the changes for this feature, making everything neat and organized)

Sorry to be so picky, but using a control like this with no background color is a must.

Also, you don't have to close and re-open pull-requests. Just commit and push to that branch and they will appear here. :)

**Comment by zhao0** [comment]
I have add you to the collaborators. 
That branch was delete by my mistake, so I re-open a pull-request. :)

**Comment by hsousa** [comment]
Hey @zhao0! I pushed the changes I was talking about. Everything should work fine now.

Take a look and let me know. If everything's good with you, I'll take care of updating the README and merging this PR.

**Comment by zhao0** [comment]
Hey @hsousa ! Everything is good with me.

**Pull request merged**
