### PR TITLE
Swift Package Manager support

### PR DESCRIPTION
**Pull request by mstfy**
Add minimal Package.swift

### CODE REVIEW

**Review by che1404 — APPROVED** [review]

**Comment by che1404** [comment]
Can we please merge this? 🙏

**Comment by hsousa** [comment]
Hi @che1404! Yes, sorry I've been meaning to pick this little control up and get it modernized. I'll do that soon and include this change! ❤️

**Comment by brightsider** [comment]
@hsousa hi, are you have some news about that?

**Comment by hsousa** [comment]
Sorry @brightsider, not really. But I'm ok with getting this merged if it helps everyone.

**Pull request merged**
