### PR TITLE
send event after user touch ended

### PR DESCRIPTION
**Pull request by ibnusina**

### CODE REVIEW

**Comment by hsousa** [comment]
I'm sorry but what's the reason for this?

Seems wrong to send an `UIControlEventEditingDidEnd` action for a control that doesn't have an editing mode.

**Comment by ibnusina** [comment]
Thank you for reviewing this. Does changing the star value means editing?

**Comment by hsousa** [comment]
When you change the star value you're certainly _editing_, but this control doesn't have an "edit mode".

For it to have an edit mode, it would have to also send `UIControlEventEditingDidBegin` and `UIControlEventEditingChanged` actions.

This only makes sense in a control like `UITextField` where there can be multiple user-generated actions/steps between an editing starting and ending. Here the editing starts and ends when the user drags their finger around and changes the rating value.

Question: what are you trying to do exactly? Maybe there's a better way. 🙂

**Comment by ibnusina** [comment]
Thank you for the explanation, I guess I need to learn more about `UIControlEvent` usage. What I'm trying to achieve is the users can get feedback after they lift their finger. For example, if user dragging around then lift his/her finger user will see an alert or directed to a new screen. Is there any better and proper way to do this?

**Comment by hsousa** [comment]
We're only sending `UIControlEventValueChanged` when tracking ends (i.e. when the user stops dragging their finger), so you can probably use that to get the behaviour you're looking for.

Hope that helps, and sorry for the late response!

Closing this PR for now, but feel free to post any further questions!

**Pull request closed without merging**
