### PR TITLE
add accurate half star

### PR DESCRIPTION
**Pull request by zhao0**

### CODE REVIEW

**Comment by zhao0** [comment]
Hi,I add a feature that the star can be render accurately for the value.

**Comment by hsousa** [comment]
Hi @zhao0! Thanks for the PR, this is an awesome idea!

I have a few issues with though:

1) When I run your sample project, I can't pan through the control to change the star value. I'm assuming this is because you added `<userDefinedRuntimeAttribute type="boolean" keyPath="enabled" value="NO"/>` in the storyboard.

2) Although I understand why you chose to have an `enum`, it would be better to have a `BOOL` property like `accurateHalfStars`. This is because `enum`s are currently not supported as `IBInspectable` properties, and why you probably had to add it manually to the storyboard with:
```xml
<userDefinedRuntimeAttribute type="number" keyPath="halfStarStyle">
    <integer key="value" value="1"/>
</userDefinedRuntimeAttribute>
```

3) When I enable the control (by removing the line on point 1) I can change the value, but it will snap to .0 or .5 values, which is the default behaviour in this control. To fully implement this feature, when `accurateHalfStars` is enabled, no snapping should occur.

Let me know what you think.

**Comment by zhao0** [comment]
When I first time implemented it, what I think was the same as you, but I got some problems.
1) If I choose to have a `BOOL` property like `isAccurateHalfStars`, people who use it may feel confused about two property, so I choose to have a `enum`. If it is necessary, I can update it.
2) When I enable the control, and change the value, I can't know the exact star value, so I give up to the implementation of no snapping. 

What you see in storyboard is the result of my dragging, I don't know how to config the property panel, so I set the `userDefinedRuntimeAttribute `

**Comment by hsousa** [comment]
You had to use `userDefinedRuntimeAttribute` because the property was an `enum`. Like I said, I totally understand your reasons for choosing so, but one of my main goals with this control is to make is easily usable in all scenarios, including a close-to-zero-lines-of-code-as-possible. :-)

For this, all properties must be fully compliant with `IBInspectable`.

Regarding this and the snapping problem, I can give it a go and try to implement it on my side when I have some time, if you don't mind.

**Comment by zhao0** [comment]
Yeah, I will update it later.

**Pull request closed without merging**
